spring:
  application:
    name: consumer-service
  jackson:
    default-property-inclusion: non_null

server:
  port: ${CONSUMER_PORT:19001}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT:17001}/eureka/

resilience4j:
  circuitbreaker:
    instances:
      crazy:
        baseConfig: default