spring:
  application:
    name: eureka-server

server:
  port: ${EUREKA_PORT:17001}

eureka:
  instance:
    appname: ${spring.application.name}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: ${EUREKA_HOST:eureka}
  server:
    enable-self-preservation: false
  client:
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT:17001}/eureka/