spring:
  application:
    name: eureka-server
server:
  port: 17002
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
