spring:
  application:
    name: gateway
  jackson:
    default-property-inclusion: non_null
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_PATH}

server:
  port: ${CONFIG_PORT:21001}

eureka:
  instance:
    appname: ${spring.application.name}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT:17001}/eureka/
