spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_PATH}

server:
  port: ${CONFIG_PORT:21001}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT:17001}/eureka/
